kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-issuer-watcher
rules:
  - apiGroups: ["", "extensions", "apps", "cert-manager.io"]
    resources: ["secrets", "certificaterequests"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-issuer
subjects:
- kind: ServiceAccount
  name: cert-manager-issuer
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cert-manager-issuer-watcher
  apiGroup: ""
